# Numpy
>~ travis Oliphnat

Numpy developed in c++

Developed specially for matrix calculation

Array is a container that contains similiar data types


In [2]:
# pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [2]:
import numpy as np


In [3]:
#integer
a = np.array([1,2,3,4,5,6,7,8,9,])
print (a)

[1 2 3 4 5 6 7 8 9]


In [4]:
#float
b = np.array([1,2,3,4,5,6,7.5,8,9,])
print (b)

[1.  2.  3.  4.  5.  6.  7.5 8.  9. ]


In [7]:
#string
c = np.array([1,2,3,4,5,6,7.5,8,9,"10"])
print (c)

['1' '2' '3' '4' '5' '6' '7.5' '8' '9' '10']


numpy convers the datatype to prevent data loss

conversion py presidence
1-String, 2-Float, 3-Integer

In [11]:
# if u dont want that numpy converts ur datatype to prevent dataloss

#float
d = np.array([1,2,3,4,5,6,7.5,8,9,],dtype=np.integer)
print (d)

# here 7.5 whiich is a float aka decimal value convert into intege

[1 2 3 4 5 6 7 8 9]


C:\Users\vikal\AppData\Local\Temp\ipykernel_9316\2166460011.py:4: DeprecationWarning: Converting `np.integer` or `np.signedinteger` to a dtype is deprecated. The current result is `np.dtype(np.int_)` which is not strictly correct. Note that the result depends on the system. To ensure stable results use may want to use `np.int64` or `np.int32`.
  d = np.array([1,2,3,4,5,6,7.5,8,9,],dtype=np.integer)


bits/bytes
int8 can store numbers from -128 to 127 
if our data is in between these nos and we using like int 64 which will consume a lot memory block and used only limited bytes so the rest will not be used so its a wastage of memory  


np.int8(-128 to 127), np.int16,np.int32, np.int64

In [12]:
import sys

In [13]:
# memory bytes consumed bye int8

e = np.array([1,2,3,4,5,6,7.5,8,9,],dtype=np.int8)
print (e)

sys.getsizeof(e)

[1 2 3 4 5 6 7 8 9]


121

In [14]:
# memory bytes consumed bye int16

f = np.array([1,2,3,4,5,6,7.5,8,9,],dtype=np.int16)
print (f)

sys.getsizeof(f)

[1 2 3 4 5 6 7 8 9]


130

In [15]:
# memory bytes consumed bye int32

g = np.array([1,2,3,4,5,6,7.5,8,9,],dtype=np.int32)
print (g)

sys.getsizeof(g)

[1 2 3 4 5 6 7 8 9]


148

In [16]:
# 2d Array

h = np.array([[1,2,3],[4,5,6]])
print(h)

[[1 2 3]
 [4 5 6]]


In [18]:
i = np.zeros((2,2))
print(i)

[[0. 0.]
 [0. 0.]]


In [20]:
# Zeros

# we were getting decimals in the previous array so we changed the data type by using dtype
# why int8 cause data range is less so why to waste memory


i = np.zeros((2,2), dtype=np.int8)
print(i)

[[0 0]
 [0 0]]


In [21]:
# Ones

j = np.ones((2,2), dtype=np.int8)
print(j)

[[1 1]
 [1 1]]


In [24]:
# Full
# using full we can use any number 
# np.full((shape),value ,dtype)

k = np.full((2,2),5, dtype=np.int8)
print(k)

[[5 5]
 [5 5]]


# Reshape & Resize

### Reshape

not even a single element can be left 

In [7]:
a = np.array([1,2,3,4,5,6,7,8,9,10])

In [8]:
a=np.array([np.random.randint(1,10)for i in range(10)])

print (a)

[7 9 6 9 2 8 7 1 6 3]


In [9]:
np.reshape(a,(5,2))

array([[7, 9],
       [6, 9],
       [2, 8],
       [7, 1],
       [6, 3]])

In [10]:
np.reshape(a,(2,5))

array([[7, 9, 6, 9, 2],
       [8, 7, 1, 6, 3]])

In [16]:
b = [1,2,3,4,5,6,7]

np.reshape(b,(1,7))



array([[1, 2, 3, 4, 5, 6, 7]])

In [15]:
np.reshape(b,(7,1))


array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7]])


# order
> by default we r using the order of c language to make the array 

c says the if it has 6 elements then the first 3 elements are on top nd the other 3 will be on bottom

fortron also make the array it has different order eg

In [19]:
# C lang order (denoted as C)
np.reshape(a,(2,5), order = 'C')

array([[7, 9, 6, 9, 2],
       [8, 7, 1, 6, 3]])

In [20]:
# Fotron lang order (denoted as F)
np.reshape(a,(2,5), order = 'F')

array([[7, 6, 2, 7, 6],
       [9, 9, 8, 1, 3]])

In [21]:
# to check the dimention of the array

np.ndim(a)

1

In [22]:
# to check the shape of the array

np.shape(a)

# 10 and nothing after comma it means one (10,1) or (10,)
#means one row 10 coloumns



(10,)

In [23]:
# we can use len fun to get the element 

len(a)

10

### Resize

elements can be left 

In [25]:
np.resize(a,(3,3))

array([[7, 9, 6],
       [9, 2, 8],
       [7, 1, 6]])

In [28]:
np.resize(np.array([i for i in range (1, 101)]),(10,10))

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [29]:
np.resize(np.array([i for i in range (1, 101)]),(9,9))

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33, 34, 35, 36],
       [37, 38, 39, 40, 41, 42, 43, 44, 45],
       [46, 47, 48, 49, 50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59, 60, 61, 62, 63],
       [64, 65, 66, 67, 68, 69, 70, 71, 72],
       [73, 74, 75, 76, 77, 78, 79, 80, 81]])

In [31]:
z = np.resize(np.array([i for i in range (1, 101)]),(10,10))

In [32]:
# indexing

z[0]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [33]:
# indexing in indexing 

z[0][0]

1

In [34]:
cont=()
for i in z :
    cont = cont +tuple(i)
print (cont)

(1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100)


### structured and unstructured dataset

In [ ]:
# 0 dimension array/ scalar array = it has only magnitude no direction
# 1 dimension array = it has both magnitude nd direction
# 2 dimension array = it has both x axis and y axis

### Multiplication of array: dot production

In [38]:
# 2,2

a = np.resize( [i for i in range (10)],(2,2))

print (a

[[0 1]
 [2 3]]


In [61]:
a = np.resize( [i for i in range (10)],(2,2))

print (a)


[[0 1]
 [2 3]]


In [62]:
# to check the shape of the array 
np.shape(a)

(2, 2)

In [63]:
# to check the dimension of the array 
np.ndim(a)

2

In [64]:
# 3,2

b = np.resize( [i for i in range (10)],(3,2))

print (b)

[[0 1]
 [2 3]
 [4 5]]


In [46]:
# to check the shape of the array 
np.shape(b)


(3, 2)

In [47]:
# to check the dimension of the array 
np.ndim(b)

2

#can we multipy array a and b ?

#no

#why?

coloumn of a shoud be eaqual to row of b only then multiplication is posssible


In [51]:
# here the multiplication is not possible 
# cause the coloumn of c is not eaqual to row of d 

# we can check the row and coloumn using np.shape

a.dot(b)

ValueError: shapes (2,2) and (3,2) not aligned: 2 (dim 1) != 3 (dim 0)

In [54]:
# 2,3

c = np.resize( [i for i in range (10)],(2,3))

print (a)


[[0 1 2]
 [3 4 5]]


In [55]:
# 3,2

d = np.resize( [i for i in range (10)],(3,2))

print (b)

[[0 1]
 [2 3]
 [4 5]]


In [57]:
# dot product of two arrays
# here the multiplication is possible 
# cause the coloumn of c is eaqual to row of d 


c.dot(d)

array([[10, 13],
       [28, 40]])

In [59]:
# another way to multiply the arrays or dot product of two arrays

c@d

array([[10, 13],
       [28, 40]])

In [65]:
# Transpose 
# to change the shape 
# imagine if the shape was like (2,3) after using transpose it will be like (3,2)

a

array([[0, 1],
       [2, 3]])

In [66]:
a.transpose()

array([[0, 2],
       [1, 3]])

In [70]:
b


array([[0, 1],
       [2, 3],
       [4, 5]])

In [71]:
b.shape

(3, 2)

In [75]:
m = b.transpose()

m

array([[0, 2, 4],
       [1, 3, 5]])

In [76]:
m.shape

(2, 3)

In [78]:
# anoter way to use transpose
b.T

array([[0, 2, 4],
       [1, 3, 5]])

In [82]:
# zero dimention array

# 0 dimention array

x = np.array(1)
x

array(1)

In [83]:
np.shape(x)

()

In [84]:
np.ndim(x)

0

In [86]:
# one dimention array

# 1 dimention array

y = np.array([1])
y

array([1])

In [88]:
np.shape(y)

(1,)

In [89]:
np.ndim(y)

1